### ISSUE TITLE
Could I define a alias ?

### ISSUE THREAD

**Issue by mallka** [vasadibt/yii2-cron#3]
I got error when I migrate/up :

Exception 'yii\base\InvalidArgumentException' with message 'Invalid path alias: @vasadibt/cron/migrations'

**Comment by fullmvc** [comment]
Yes, you can define an alias like this:
`Yii::setAlias('@vasadibt', '/path/to/vasadibt');`
But it seams like a bug...

**Comment by vasadibt** [comment]
I don't understand, because I install a clean `yii2-app-advanced` and install the `yii2-cron`  and when I tested both way of migration run, and they was successful run.
If you use composer when install the package than automaticly configure `@vasadibt/cron` alias.

Can you write your steps what try to install and run the migrations?
